services:
  service-auth:
    build: .
    container_name: service-auth
    labels:
      logging: "promtail"
      service: "service-auth"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=service-auth
      - OTEL_RESOURCE_ATTRIBUTES=service.name=service-auth,deployment.environment=development
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    ports:
      - "3004:3000"
    env_file:
      - .env
    networks:
        - hubert-network

volumes:
  mongo_data:

networks:
  hubert-network:
    external: true